version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - cd $(pyenv root) && git pull --rebase --autostash --ff-only && cd - && pyenv --version
      - pyenv install -s
      - pip install --upgrade pip
      - pip install poetry awscli
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  build:
    commands:
      - make build
cache:
  paths:
    - '/root/.pyenv/versions/3.9.5'
