version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  build:
    commands:
      - make build
